# Generated by Django 3.2.8 on 2021-11-21 18:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(default=datetime.datetime(2021, 11, 21, 18, 15, 33, 610831, tzinfo=utc))),
                ('end_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('numOfRecruitment', models.IntegerField(default=18)),
                ('completed', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Account.host')),
            ],
        ),
        migrations.CreateModel(
            name='Game_Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('game', 'user')},
            },
        ),
    ]
