# Generated by Django 3.2.8 on 2021-11-21 18:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 21, 18, 18, 8, 139242, tzinfo=utc)),
        ),
    ]
