# Generated by Django 3.2.8 on 2021-12-06 11:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_auto_20211206_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 11, 33, 26, 758535, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 11, 33, 26, 615527, tzinfo=utc)),
        ),
    ]
