# Generated by Django 3.2.8 on 2021-12-07 11:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_auto_20211206_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='numOfParticipation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 11, 2, 50, 846813, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 11, 2, 50, 702837, tzinfo=utc)),
        ),
    ]
