# Generated by Django 3.2.8 on 2021-12-08 07:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0004_auto_20211207_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 7, 54, 39, 837080, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 7, 54, 39, 713079, tzinfo=utc)),
        ),
    ]
