# Generated by Django 3.2.8 on 2021-12-08 08:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0005_auto_20211208_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 8, 35, 42, 406952, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 8, 35, 42, 288967, tzinfo=utc)),
        ),
    ]
