# Generated by Django 3.2.8 on 2021-12-11 10:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0006_auto_20211208_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 11, 10, 19, 3, 411069, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 11, 10, 19, 3, 296070, tzinfo=utc)),
        ),
    ]
