# Generated by Django 3.2.8 on 2022-04-16 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('numOfRecruitment', models.IntegerField(default=18)),
                ('numOfParticipation', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accounts.host')),
            ],
        ),
        migrations.CreateModel(
            name='HostGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.game')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.host')),
            ],
        ),
        migrations.CreateModel(
            name='Game_Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('game', 'user')},
            },
        ),
    ]
