# Generated by Django 3.2.8 on 2022-03-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20220308_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='end_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_datetime',
            field=models.DateTimeField(),
        ),
    ]
