# Generated by Django 3.2.8 on 2021-11-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='group_name',
            field=models.CharField(default='veterans', max_length=20, verbose_name='모임 이름'),
        ),
        migrations.AddField(
            model_name='hostapplication',
            name='group_name',
            field=models.CharField(default='veterans', max_length=20, verbose_name='모임 이름'),
        ),
    ]
