# Generated by Django 3.2.8 on 2022-04-01 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_hostapplication_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(regex='^01([0|1|6|7|8|9])-?([1-9][0-9]{2,3})-?([0-9]{4})$')], verbose_name='전화 번호'),
        ),
    ]
