# Generated by Django 3.2.8 on 2021-12-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_user_is_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(default=False, max_length=100, unique=True),
        ),
    ]
