# Generated by Django 3.2.8 on 2022-04-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comment_type',
        ),
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.CharField(max_length=100, null=True, verbose_name='평가'),
        ),
    ]
