# Generated by Django 3.2.8 on 2021-12-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment_type',
            field=models.IntegerField(choices=[(1, '위험한 플레이를 해요'), (2, '독단적인 플레이를해요'), (3, '이타적인 플레이를 해요'), (4, '실력이 출중한 선수에요'), (5, '매너가 좋은 선수에요')], max_length=30),
        ),
    ]
