# Generated by Django 3.2.8 on 2021-12-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_alter_review_comment_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('reviewer', 'reviewee')},
        ),
        migrations.RemoveField(
            model_name='review',
            name='game',
        ),
    ]
